config = {
    'model_name': 'pickle_test_load',
    'mode': 'single',
    'load': True,
    'model_to_load': 'test',
    'n_episodes': 1000,
    'epsilon': 0.5,
    'eps_min': 0.01,
    'checkpoint_every': 100,
    'learn_frequency': 100,
    'learn_amount': 100,
    'gamma': 0.99,
    'learning_rate': 0.0001,
    'memory_size': 50000,
    'batch_size': 32,
    'replace_network_frequency': 100,
    'eps_dec': 1e-5,
    'invalid_moves_enabled': False,
}