config = {
    'model_name': 'model2',
    'mode': 'single',
    'load': False,
    'model_to_load': None,
    'n_episodes': 300000,
    'epsilon': 1,
    'eps_min': 0.01,
    'checkpoint_every': 1000,
    'learn_frequency': 100,
    'learn_amount': 30,
    'gamma': 0.99,
    'learning_rate': 0.0001,
    'memory_size': 50000,
    'batch_size': 32,
    'replace_network_frequency': 1000,
    'eps_dec': 1e-5,
    'invalid_moves_enabled': True,
    'opponent': "RL",
    'network': "2X8",
    'canals': 3,
    'epsilon_softmax': True,
    'adamw_optimizer': False,
    'dropout': False
}